apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder-service
  labels:
    app: adder-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adder-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: adder-service
    spec:
      containers:
      - name: adder-service
        image: adder-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: PORT
          value: "5000"