apiVersion: v1
kind: Service
metadata:
  name: document-analytics-api
  labels:
    app: document-analytics
    component: api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    name: http
  selector:
    app: document-analytics
    component: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-analytics-api
  labels:
    app: document-analytics
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-analytics
      component: api
  template:
    metadata:
      labels:
        app: document-analytics
        component: api
    spec:
      serviceAccountName: document-analytics-api
      containers:
      - name: api
        image: document-analytics:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: shared-documents
          mountPath: /app/data
        - name: sample-documents
          mountPath: /documents
      volumes:
      - name: shared-documents
        emptyDir: {}
      - name: sample-documents
        configMap:
          name: sample-documents