apiVersion: v1
kind: ServiceAccount
metadata:
  name: document-analytics-api
  labels:
    app: document-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: document-analytics-api-role
  labels:
    app: document-analytics
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: document-analytics-api-role-binding
  labels:
    app: document-analytics
subjects:
- kind: ServiceAccount
  name: document-analytics-api
  namespace: default
roleRef:
  kind: Role
  name: document-analytics-api-role
  apiGroup: rbac.authorization.k8s.io